# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: state_root_test

on:
  push:
    branches: ["main"]
    paths-ignore:
      - "**/docs/**"
      - "**/README.md"
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "**/docs/**"
      - "**/README.md"

jobs:
  test-state-root:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Build State Root Test
        run: make build_state_root_test
      - name: Clean Env
        run: make reset
      - name: Run State Root Gen Test
        run: make state_root_test_gen
      - name: Clean Env
        run: make reset
      - name: Run State Root Assert Test
        run: make state_root_test_assert
